name: 'Telegram notifier'
description: 'Node.js based github action for notifying things to telegram'
inputs:
	status:
		description: 'Job status'
		required: true
runs:
	using: 'node12'
	main: 'index.js'