name: 'Telegram notifier'
description: 'Node.js based github action for notifying things to telegram'
inputs:
  status:
    description: 'Job status'
    required: true
  bot:
    description: 'Telegram bot token'
    required: true
  channel:
    description: 'Integer or string: Chat/channel id'
    required: true
  initial:
    description: 'If true, deployment has just started'
    required: false
runs:
  using: 'node12'
  main: 'index.js'